apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orange
  name: orange
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orange
  strategy: {}
  template:
    metadata:
      labels:
        app: orange
    spec:
      containers:
      - image: khaledghazal/orange-httpd:omar
        name: orange-httpd
